### ISSUE TITLE
Extension fails with latest website

### ISSUE THREAD

**Issue by larzm42** [gallmarch/fl-conversion-helper#1]
When loading the Possessions tab, the following error is produced in the console and the extension does not function.

content-script.js:66 Uncaught (in promise) TypeError: Cannot read property 'find' of undefined
    at content-script.js:66
(anonymous) @ content-script.js:66
Promise.then (async)
(anonymous) @ content-script.js:66
(anonymous) @ content-script.js:6
(anonymous) @ content-script.js:30
value @ content-script.js:66
br @ content-script.js:6
gr @ content-script.js:6
vr @ content-script.js:6
dr @ content-script.js:6
or @ content-script.js:6
Cr @ content-script.js:6
kr @ content-script.js:6
Nr.render @ content-script.js:14
(anonymous) @ content-script.js:6
Er @ content-script.js:6
Ar @ content-script.js:6
render @ content-script.js:14
r @ content-script.js:66
i @ content-script.js:43
callback @ content-script.js:43
e.observerCallback @ content-script.js:6
(anonymous) @ content-script.js:6

**Comment by sdob** [comment]
Thanks for this! I will take a look. What browser are you on? FWIW, I can't confirm this on Chrome 73.0.3683.75 or Firefox 65.0.1 (both under Linux).

There is an issue with certain Chrome installations where a currently-active field test is breaking XHRs in browser extensions: I posted [a fix on the FBG forums](http://community.failbettergames.com/topic27376-psa-conversion-helper-and-goat-farmer-on-chrome.aspx), which has worked for a few people. Can you try the linked approach and get back to me if it solves/fails to solve the issue?

**Comment by larzm42** [comment]
Thanks, the setting in Chrome fixed the issue for me.

**Comment by sdob** [comment]
Brilliant! Thanks for confirming; I appreciate the heads-up in any case.
